targets:
  $default:
    builders:
      sfw_generator:
        enabled: true

builders:
  sfw_flutter:
    target: ":sfw_generator"
    import: "package:sfw_generator/builder.dart"
    builder_factories: ["db"]
    build_extensions: {".dart": [".sfw.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
